/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.fileutils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FileUtilsTest {
    @Test void appHasAGreeting() {
        FileUtils classUnderTest = new FileUtils();
        //assertNotNull(classUnderTest(), "app should have a greeting");
    }
}
