/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cat.uvic.teknos.m06.fileutils;


import java.io.File;



public class FileUtils {

    public static boolean isValidDirectory(String path){
        File file = new File(path);


        if(!file.exists()){
            return false;
        }

        if(!file.isDirectory()){
            return false;
        }

        if(file.listFiles().length > 0){
            return false;
        }

        if(file.getAbsolutePath().contains(" ")){
            return false;
        }

        return true;
    }
    public static void main(String[] args) {

        //System.out.println(isValidDirectory("C:\\Users\\10011093\\OneDrive - Universitat de Vic\\Escritorio\\porves") );
        //System.out.println(isValidDirectory("C:\\Users\\10011093\\source\\repos\\proves"));
    }
}
