/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cat.uvic.teknos.m06.fileutils;


import java.io.File;



public class FileUtils {


    public static void main(String[] args) {

        System.out.println( "hola");
    }
}
